### ISSUE TITLE
Use optional route parameters

### ISSUE THREAD

**Issue by nizos** [CloudCannon/sveltekit-bookshop-starter#2]
A simple change to the `src/routes` directory can make it easier to create and use new pages in the `content/pages` directory out of the box.

For example, creating a `content/pages/about.md` file at the moment does not result in a page that can be reached at `/about` in the browser.
However, by creating a `src/routes/[[slug]]` directory and moving the following files into it it solves the problem:
- `src/routes/+page.server.js`
- `src/routes/+page.svelte`

The double brackets, instead of single brackets, makes the slug optional. Allowing it to handle both `index.md` (`/`) and slugs of any pages created in `content/pages`.

This might be helpful for people new to SvelteKit and want to get started.
Would you like me to submit a pull request with the above changes? :)

**Comment by nizos** [comment]
One minor adjustment to `+page.svelte` might also be required if this change is to be implemented.

Change:
```js
export let data;
let pageDetails = data.data;
```

to:
```js
export let data;
let pageDetails;

$: {
    pageDetails = data.data;
}
```

That is so that the pages render correctly after navigating without the need for a full page refresh.

We will also need to update the following part in `svelte.config.js` from:
```js
prerender: {
    handleHttpError: 'warn',
}
```

To:
```js
prerender: {
    crawl: true,
    entries: ['/', '*'],
    handleHttpError: 'warn',
}
```

So that the `/` page and other pages get pre-rendered.

**Comment by NJKode** [comment]
Thanks for this! This is a great suggestion which we'll look to implement in the near future (probably within 2 weeks).

(Sorry for the late response, this somehow escaped my attention)
